# Generated by Django 5.0.4 on 2024-04-27 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='delivery.client'),
            preserve_default=False,
        ),
    ]
