# Generated by Django 5.0.4 on 2024-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_location_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='delivery.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='etat',
            field=models.CharField(choices=[('L', 'Livraison'), ('A', 'Attente'), ('O', 'Off')], default='O', max_length=1),
        ),
    ]
