# Generated by Django 5.0.4 on 2024-04-28 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_commande_client_commande_livreur_livreur_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 16, 53, 29, 800588)),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='matricule',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='matricule',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
