# Generated by Django 5.0.4 on 2024-04-28 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_client_birthdate_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 19, 55, 13, 446639, tzinfo=datetime.timezone.utc)),
        ),
    ]
