# Generated by Django 5.0.4 on 2024-04-30 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_client_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='matricule',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='utilisateur',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='nom utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='utilisateur',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='nom utilisateur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 8, 48, 49, 323612, tzinfo=datetime.timezone.utc)),
        ),
    ]
