# Generated by Django 5.0.4 on 2024-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_client_matricule_remove_livreur_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
