# Generated by Django 5.0.4 on 2024-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_client_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='utilisateur',
            field=models.CharField(max_length=10, unique=True, verbose_name='Nom utilisateur'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='note',
            field=models.FloatField(verbose_name='Moyenne des notes'),
        ),
    ]
