# Generated by Django 5.0.4 on 2024-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_client_birthdate_alter_client_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='utilisateur',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom utilisateur'),
        ),
    ]
