# Generated by Django 5.0.4 on 2024-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_client_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='localisation',
            field=models.TextField(),
        ),
    ]
