# Generated by Django 5.0.4 on 2024-05-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_restaurant_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='note',
            field=models.FloatField(default=0),
        ),
    ]
