# Generated by Django 5.0.4 on 2024-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_livreur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='note',
            field=models.FloatField(default=0, verbose_name='Moyenne des notes'),
        ),
    ]
