# Generated by Django 5.0.4 on 2024-05-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_livreur_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_debut_cuisson',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_debut_livraison',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_fin_cuisson',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_fin_livraison',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.livreur'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plats', to='delivery.restaurant'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande', to='delivery.commande'),
        ),
        migrations.AlterField(
            model_name='repas',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plat', to='delivery.plat'),
        ),
    ]
