# Generated by Django 5.0.4 on 2024-05-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_alter_commande_date_debut_cuisson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='delivery.client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='repas',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repas', to='delivery.commande'),
        ),
    ]
